### ISSUE TITLE
note for all people who dunno how to fix this 

### ISSUE THREAD

**Issue by HertZxD** [dartZXC/HertZ-inzernal-modified#1]
dont dm me for help mf, solve all error by ur self

how to fix it?
update sigs to 3.64
fix broken UpdateProcessTankPacket

pathfinder sometime crash?
fix it by ur self wth

why the code is messy?
i can't code :(

------------------------
edit by Laaru (one of the repository maintainers): UpdateProcessTankPacket is fixed

**Comment by aSecdev** [comment]
"i can't code :(" lol ?
You are good at it 
Good work :3

**Comment by GoodPog** [comment]
hey hertz stfu and thanks :)

**Comment by xuzzzze** [comment]
k

**Comment by yEsPaP** [comment]
hi i just want to ask what  "only crystal" command should do

**Comment by GoodPog** [comment]
> hi i just want to ask what "only crystal" command should do

it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.

**Comment by yEsPaP** [comment]
> > hi i just want to ask what "only crystal" command should do
> 
> it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.
> 
> you can't see it yourself but others do.

code in autocollect you send packet type 11. from where you got this info?

im trying same thing, but with drop packet and its not working
```
        GameUpdatePacket packet{ 0 };
        packet.type = 13;
        packet.item_id = 5033;
        packet.lost_item_count = 1;
        packet.build_range = 1;
        SendPacketRawHook::Execute(4, &packet, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
        GameUpdatePacket packetz{ 0 };
        packetz.type = 14;
        packetz.item = 1;
        packetz.item_id = 5033;
        packetz.pos_x = 620;
        packetz.pos_y = 773;
        packetz.tiles_length = 1;
        SendPacketRawHook::Execute(4, &packetz, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
```
(got values using printf)

then i check debug of collect packet
and got
```
packet.type = 14;
packet->item: -1
packet->item_id: 38
packet->tiles_length: -1
```

so from where you got the values?

**Comment by pokzy** [comment]
how can i find the valid UpdateProcessTankPacket?

**Comment by pokzy** [comment]
> > > hi i just want to ask what "only crystal" command should do
> > 
> > 
> > it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.
> > you can't see it yourself but others do.
> 
> code in autocollect you send packet type 11. from where you got this info?
> 
> im trying same thing, but with drop packet and its not working
> 
> ```
>         GameUpdatePacket packet{ 0 };
>         packet.type = 13;
>         packet.item_id = 5033;
>         packet.lost_item_count = 1;
>         packet.build_range = 1;
>         SendPacketRawHook::Execute(4, &packet, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
>         GameUpdatePacket packetz{ 0 };
>         packetz.type = 14;
>         packetz.item = 1;
>         packetz.item_id = 5033;
>         packetz.pos_x = 620;
>         packetz.pos_y = 773;
>         packetz.tiles_length = 1;
>         SendPacketRawHook::Execute(4, &packetz, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
> ```
> 
> (got values using printf)
> 
> then i check debug of collect packet and got
> 
> ```
> packet.type = 14;
> packet->item: -1
> packet->item_id: 38
> packet->tiles_length: -1
> ```
> 
> so from where you got the values?

do you know how to send punch packet in x, y pos?

**Comment by yEsPaP** [comment]
> > > > hi i just want to ask what "only crystal" command should do
> > > 
> > > 
> > > it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.
> > > you can't see it yourself but others do.
> > 
> > 
> > code in autocollect you send packet type 11. from where you got this info?
> > im trying same thing, but with drop packet and its not working
> > ```
> >         GameUpdatePacket packet{ 0 };
> >         packet.type = 13;
> >         packet.item_id = 5033;
> >         packet.lost_item_count = 1;
> >         packet.build_range = 1;
> >         SendPacketRawHook::Execute(4, &packet, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
> >         GameUpdatePacket packetz{ 0 };
> >         packetz.type = 14;
> >         packetz.item = 1;
> >         packetz.item_id = 5033;
> >         packetz.pos_x = 620;
> >         packetz.pos_y = 773;
> >         packetz.tiles_length = 1;
> >         SendPacketRawHook::Execute(4, &packetz, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (got values using printf)
> > then i check debug of collect packet and got
> > ```
> > packet.type = 14;
> > packet->item: -1
> > packet->item_id: 38
> > packet->tiles_length: -1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so from where you got the values?
> 
> do you know how to send punch packet in x, y pos?

gt::hit_tile

**Comment by Sahyui** [comment]
**_Did anyone know how to fix this ? _UpdateProcessTankPacket_ help_**

**Comment by pokzy** [comment]
> > > hi i just want to ask what "only crystal" command should do
> > 
> > 
> > it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.
> > you can't see it yourself but others do.
> 
> code in autocollect you send packet type 11. from where you got this info?
> 
> im trying same thing, but with drop packet and its not working
> 
> ```
>         GameUpdatePacket packet{ 0 };
>         packet.type = 13;
>         packet.item_id = 5033;
>         packet.lost_item_count = 1;
>         packet.build_range = 1;
>         SendPacketRawHook::Execute(4, &packet, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
>         GameUpdatePacket packetz{ 0 };
>         packetz.type = 14;
>         packetz.item = 1;
>         packetz.item_id = 5033;
>         packetz.pos_x = 620;
>         packetz.pos_y = 773;
>         packetz.tiles_length = 1;
>         SendPacketRawHook::Execute(4, &packetz, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
> ```
> 
> (got values using printf)
> 
> then i check debug of collect packet and got
> 
> ```
> packet.type = 14;
> packet->item: -1
> packet->item_id: 38
> packet->tiles_length: -1
> ```
> 
> so from where you got the values?

hi, how you debugged packet?

**Comment by Gatyu388** [comment]
> > > hi i just want to ask what "only crystal" command should do
> > 
> > 
> > it's like umm u use it when u use Sum Packet_STATE, it basically just throws crystals at everyone in the world.
> > you can't see it yourself but others do.
> 
> code in autocollect you send packet type 11. from where you got this info?
> 
> im trying same thing, but with drop packet and its not working
> 
> ```
>         GameUpdatePacket packet{ 0 };
>         packet.type = 13;
>         packet.item_id = 5033;
>         packet.lost_item_count = 1;
>         packet.build_range = 1;
>         SendPacketRawHook::Execute(4, &packet, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
>         GameUpdatePacket packetz{ 0 };
>         packetz.type = 14;
>         packetz.item = 1;
>         packetz.item_id = 5033;
>         packetz.pos_x = 620;
>         packetz.pos_y = 773;
>         packetz.tiles_length = 1;
>         SendPacketRawHook::Execute(4, &packetz, 56, NULL, sdk::GetPeer(), ENET_PACKET_FLAG_RELIABLE);
> ```
> 
> (got values using printf)
> 
> then i check debug of collect packet and got
> 
> ```
> packet.type = 14;
> packet->item: -1
> packet->item_id: 38
> packet->tiles_length: -1
> ```
> 
> so from where you got the values?

bro u know how to send wrench_tile packet?

**Comment by yEsPaP** [comment]
> 

gt::wrench_tile(CL_Vec2f(x, y))

**Comment by Gatyu388** [comment]
> > 
> 
> gt::wrench_tile(CL_Vec2i(x, y))

https://prnt.sc/22rq5dd
` if (ImGui::Button("Wrench"))
    {
        gt::wrench_tile(CL_Vec2i(13, 24));
    }`

I do it like that, but it doesnt work for some reason.. When i click button nothing happen

**Comment by Gatyu388** [comment]
I cant get the functions that send packets working

`  if (ImGui::Button("Wrench"))
    {
        gt::wrench_tile(CL_Vec2i(13, 24));
    }

    if (ImGui::Button("Break"))
    {
        gt::hit_tile(CL_Vec2i(13, 24));
    }`

I do this for hit_tile and wrench_tile but they dont seem to work, the functions hit_tile and wrench_tile do get called correctly but theres a issue at the end of both functions(gt::send doesnt work properly) that i cant understand.. does anyone have an example for sending packets ?
