### ISSUE TITLE
How do you use "bot" 

### ISSUE THREAD

**Issue by opticbird** [dartZXC/HertZ-inzernal-modified#6]
seems to be somewhat pasted from Automic, is it working or just there for no reason?

**Comment by dartZXC** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD AUTOMIC?
MATE this is alll from inzernal,
nothing is pasted
"bot"? that doesnt exist if so somebody has uploaded it not me.

**Comment by opticbird** [comment]
> XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD AUTOMIC?
> MATE this is alll from inzernal,
> nothing is pasted
> "bot"? that doesnt exist if so somebody has uploaded it not me.

Thank you for the very mature and kind response. 

https://github.com/dartZXC/HertZ-inzernal-modified/blob/main/INZERNAL/bot/ENetClient2.cpp
what is the purpose of this?

**Comment by verticalsync** [comment]
> seems to be somewhat pasted from Automic, is it working or just there for no reason?

at the least automic has skidded code from inzernal

**Comment by playingoDEERUX** [comment]
@opticbird Inzernal is something different than automic, it doesnt look like anyone unlawfully pasted anyone else here.. Also @purpl3r0se Automic has nothing to do with inzernal - neither was anything taken from inzernal, to be honest at the time of making automic with my friends (when it wasnt open src yet), I didnt even know what inzernal is. I found that out bit later

**Comment by verticalsync** [comment]
> @opticbird Inzernal is something different than automic, it doesnt look like anyone unlawfully pasted anyone else here.. Also @purpl3r0se Automic has nothing to do with inzernal - neither was anything taken from inzernal, to be honest at the time of making automic with my friends (when it wasnt open src yet), I didnt even know what inzernal is. I found that out bit later

as far as I remember, I'm pretty sure someone said some stuff was taken out of inzernal but that's as far as I remember and mightve been incorrect

**Comment by playingoDEERUX** [comment]
Automic code is open src for long time now. If you want to see if it's true for yourself you can just check the code and see if smth is taken from inzernal.. - I can just say myself I haven't even looked a split second into the inzernal code when coding automic. it wouldn't even work that well, automic is android cheat while inzernal is windows, there are some differences indeed.
