### ISSUE TITLE
Crash when entering to any world

### ISSUE THREAD

**Issue by opticbird** [dartZXC/HertZ-inzernal-modified#7]

**Comment by iProB1** [comment]
HertZ said:
update sigs to 3.67
fix broken UpdateProcessTankPacket
-----------------------------------------
You need fix or you cant  use

**Comment by Sahyui** [comment]
> ## HertZ said:
> update sigs to 3.67
> fix broken UpdateProcessTankPacket
> You need fix or you cant use

what is UpdateProcessTankPacket this? Anyone know?
