### ISSUE TITLE
How to send wrench packet ? 

### ISSUE THREAD

**Issue by Gatyu388** [dartZXC/HertZ-inzernal-modified#8]
Guys who know how to send wrench packet?

Im trying send wrench packet like this:
while(1)
{
   if (GetAsyncKeyState(VK_INSERT) & 1)
        {
            CL_Vec2i coords{ 13,24 };
            gt::wrench_tile(coords);
        }
}
this code is in dllmain.cpp why no work?

**Comment by Zawaer** [comment]
because you put it in dllmain.cpp, you need to put in somewhere else

first learn to code, then ask :)

**Comment by Gatyu388** [comment]
> because you put it in dllmain.cpp, you need to put in somewhere else
> 
> first learn to code, then ask :)

That has nothing to do with someone not knowing how to code + it wasnt caused by the code being at dllmain.cpp i debugged it and realized it. I believe you are the one who has no clue why its not working while i do have a little clue and that clue being the gt::send function not working. Im asking why the gt::send function doesnt send the packet properly.

framework.cpp
```
 if (ImGui::Button("Wrench"))
    {
        gt::wrench_tile(CL_Vec2i(13, 24));
    }
```

 ```
   if (ImGui::Button("Break"))
    {
        gt::hit_tile(CL_Vec2i(13, 24));
    }
```

I do this for hit_tile and wrench_tile but they dont seem to work, the functions hit_tile and wrench_tile do get called correctly but theres a issue at the end of both functions(gt::send doesnt work properly) that i cant understand.. does anyone have an example for sending packets ?

![image](https://user-images.githubusercontent.com/96012151/146649800-06622fb5-944d-4db6-be4f-e611684b3aec.png)
It sends the packet, but doesnt wrench it..

**Comment by verticalsync** [comment]
i usually use

SendPacketHook::Execute(int type, string packet, ENetPeer* peer)

theres also

SendPacketRawHook::Execute()

I forgot what you need to pass in to this, so you're better off checking urself.

**Comment by pokzy** [comment]
gt::wrench_tile(x, y);

**Comment by verticalsync** [comment]
> gt::wrench_tile(x, y);

almost like he already tried this, atleast read what he said.

**Comment by Gatyu388** [comment]
i fixed the issue, the wrench packet was a wrong packet... since i had a very old version of inzernal source.
